# Generated by Django 3.2.19 on 2023-06-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
